// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Tests.Automation.Features.Payments
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CreatePaymentByMethodFeature : object, global::Xunit.IClassFixture<CreatePaymentByMethodFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Payments", "Create payment by method", "As a user\nI want to create payments using different methods\nSo that country-speci" +
                "fic methods are covered", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public CreatePaymentByMethodFeature(CreatePaymentByMethodFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Payments/CreatePaymentByMethod.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create UK cheque payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create payment by method")]
        [global::Xunit.TraitAttribute("Description", "Create UK cheque payment")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "payment")]
        [global::Xunit.TraitAttribute("Category", "cheque")]
        public async global::System.Threading.Tasks.Task CreateUKChequePayment()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "payment",
                    "cheque"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create UK cheque payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I log in as \"initiator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I open the Create Payment page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I choose payment method \"cheque\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I enter cheque number \"CHQ-001234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I submit the payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("I should be on the payments list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create UK credit card payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create payment by method")]
        [global::Xunit.TraitAttribute("Description", "Create UK credit card payment")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "payment")]
        [global::Xunit.TraitAttribute("Category", "card")]
        public async global::System.Threading.Tasks.Task CreateUKCreditCardPayment()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "payment",
                    "card"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create UK credit card payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I log in as \"initiator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I open the Create Payment page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I choose payment method \"credit card\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I enter card number \"4111111111111111\" and expiry \"12/29\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I submit the payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("I should be on the payments list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create EU PayPal payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create payment by method")]
        [global::Xunit.TraitAttribute("Description", "Create EU PayPal payment")]
        [global::Xunit.TraitAttribute("Category", "ui")]
        [global::Xunit.TraitAttribute("Category", "payment")]
        [global::Xunit.TraitAttribute("Category", "paypal")]
        public async global::System.Threading.Tasks.Task CreateEUPayPalPayment()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "payment",
                    "paypal"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create EU PayPal payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("I log in as \"initiator\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
                await testRunner.AndAsync("I open the Create Payment page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I choose payment method \"paypal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.AndAsync("I enter PayPal email \"payer@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
                await testRunner.WhenAsync("I submit the payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
                await testRunner.ThenAsync("I should be on the payments list", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreatePaymentByMethodFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreatePaymentByMethodFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
